workflows:
  ios-build:
    name: Tonkeeper iOS Build
    instance_type: mac_mini_m2
    environment:
      xcode: latest
    scripts:
      - name: Build IPA
        script: |
          xcodebuild -project Tonkeeper.xcodeproj \
                     -scheme Tonkeeper \
                     -configuration Release \
                     -sdk iphoneos \
                     -derivedDataPath build
    artifacts:
      - build/Build/Products/Release-iphoneos/*.ipa
